### ISSUE TITLE
.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)

### ISSUE THREAD

**Issue by TimB0** [wvanbergen/chunky_png#159]
| ~/Dropbox/workspace/ROR/tutorial-capybara-ruby-basic @ home (discocide666) 
| => bundle exec ruby simple_test_script.rb
/Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:4:in `rescue in <top (required)>': The `SortedSet` class has been extracted from the `set` library.You must use the `sorted_set` gem or other alternatives. (RuntimeError)
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:1:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:13:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:13:in `<module:ChunkyPNG>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:1:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png.rb:150:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png.rb:150:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oily_png-1.2.0/lib/oily_png.rb:1:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oily_png-1.2.0/lib/oily_png.rb:1:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/applitools/chunky_png_patch.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/applitools/chunky_png_patch.rb:3:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/eyes_core.rb:66:in `require_relative'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/eyes_core.rb:66:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_selenium-3.17.23/lib/eyes_selenium.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_selenium-3.17.23/lib/eyes_selenium.rb:3:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_capybara-3.17.23/lib/eyes_capybara.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_capybara-3.17.23/lib/eyes_capybara.rb:3:in `<top (required)>'
	from simple_test_script.rb:1:in `require'
	from simple_test_script.rb:1:in `<main>'
/Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:2:in `require': cannot load such file -- sorted_set (LoadError)
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/3.0.0/set/sorted_set.rb:2:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:13:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:13:in `<module:ChunkyPNG>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png/palette.rb:1:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png.rb:150:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/chunky_png-1.3.6/lib/chunky_png.rb:150:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oily_png-1.2.0/lib/oily_png.rb:1:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/oily_png-1.2.0/lib/oily_png.rb:1:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/applitools/chunky_png_patch.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/applitools/chunky_png_patch.rb:3:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/eyes_core.rb:66:in `require_relative'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_core-3.17.23/lib/eyes_core.rb:66:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_selenium-3.17.23/lib/eyes_selenium.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_selenium-3.17.23/lib/eyes_selenium.rb:3:in `<top (required)>'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_capybara-3.17.23/lib/eyes_capybara.rb:3:in `require'
	from /Users/discocide666/.rbenv/versions/3.0.0/lib/ruby/gems/3.0.0/gems/eyes_capybara-3.17.23/lib/eyes_capybara.rb:3:in `<top (required)>'
	from simple_test_script.rb:1:in `require'
	from simple_test_script.rb:1:in `<main>'

**Comment by TimB0** [comment]
this is a bug in 'eyes_capybara'
