### ISSUE TITLE
undefined method size for nil:NilClass in gem install

### ISSUE THREAD

**Issue by smranta** [wvanbergen/chunky_png#37]
"undefined method `size' for nil:NilClass" error while installing chunky_png gem 
ruby 2.0.0p247 (2013-06-27 revision 41674) [x86_64-linux]

```
$ gem install chunky_png -v '1.2.8' --backtrace
ERROR:  While executing gem ... (NoMethodError)
    undefined method `size' for nil:NilClass
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package/tar_reader/entry.rb:127:in `read'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:289:in `block in digest'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:286:in `each'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:286:in `digest'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:526:in `block in verify_files'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:64:in `each'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:517:in `verify_files'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:474:in `block (2 levels) in verify'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package/tar_reader.rb:28:in `new'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:471:in `block in verify'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:470:in `open'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:470:in `verify'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/package.rb:451:in `spec'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/installer.rb:190:in `spec'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/installer.rb:493:in `ensure_loadable_spec'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/installer.rb:756:in `pre_install_checks'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/installer.rb:207:in `install'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/dependency_installer.rb:372:in `block in install'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `each'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `each_with_index'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/dependency_installer.rb:332:in `install'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/commands/install_command.rb:166:in `block in execute'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `each'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/commands/install_command.rb:158:in `execute'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/command.rb:305:in `invoke_with_build_args'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/command_manager.rb:170:in `process_args'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/command_manager.rb:130:in `run'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/lib/ruby/2.0.0/rubygems/gem_runner.rb:60:in `run'
    /home/smr/.rvm/rubies/ruby-2.0.0-p247/bin/gem:21:in `<main>'
```

**Comment by quyendam2612** [comment]
@wvanbergen love you so much.. work like a charm (inlove)

**Comment by huayangyu** [comment]
Thanks very very much!
I fix this by:
1.rm -rf the specific gem in /Library/Ruby/Gems/2.0.0/cache/
2.sudo chmod 777 /usr/bin/pod
3.sudo gem install -n /usr/local/bin specific.gem
~feel happy!
